### ISSUE TITLE
[Linux Plugin Test App] runs in Debug, not AOT

### ISSUE THREAD

**Issue by jwinarske** [meta-flutter/meta-flutter#115]
The Linux Dart code runs as expected in debug build, not with AOT.

This issue only affects plugins that select between platform code at build time using pubspec.yaml constructs.

One problematic example:
https://github.com/flutter/plugins/blob/main/packages/path_provider/path_provider/pubspec.yaml#L20
in conjunction with 
https://github.com/flutter/plugins/blob/main/packages/path_provider/path_provider_linux/pubspec.yaml#L16

Stuart's proposal is to implement an environmental variable used at flutter build time to select platform.

https://github.com/flutter/flutter/issues/103660

**Comment by rzr** [comment]
Is this related to this issue i am observing in kirkstone branch: "VM snapshot invalid and could not be inferred from settings."

Same as previously reported issue  https://github.com/jwinarske/meta-flutter/issues/36

**Comment by jwinarske** [comment]
@rzr unrelated.  The Dart VM version in Flutter SDK used to build a Flutter application must match Dart VM in engine used.  It's a 1:1 relationship.  You can send arg to VM via command line to skip this check for development scenarios.  See the Dart VM arg list in source.

**Comment by jwinarske** [comment]
I have figured this one out.  Staging a fix now.

**Comment by jwinarske** [comment]
https://github.com/meta-flutter/meta-flutter/pull/344

**Comment by matsch82** [comment]
This issue is still present for me with Flutter 3.16.7 from https://github.com/meta-flutter/meta-flutter/commit/8e0d313901b7da4d1a2ee434075c34aeb8e35439
and it does not always occur.  VideoPlayer is running fine with the Plugin Implementation from [flutter-elinux-plugins](https://github.com/sony/flutter-elinux-plugins) , while Camera Plugin shows the bug.

The elinux platform plugin is simply not loaded in release builds of the camera demo app.

I try to update to lates kirkstone version, lets see if it is fixed there.
